use anchor_lang::prelude::*;
use anchor_lang::system_program;

declare_id!("GxjDdaFVdmnov1PEccT9kt6E7b2i5MLUdTzqvA4d7a2Y");

const DOMAIN_COST: u64 = 20_000_000; // 0.02 SOL
const YEAR_SECONDS: i64 = 31536000; // 1 year

#[program]
pub mod carv_domain {
    use super::*;

        pub fn register(ctx: Context<Register>, name: String) -> Result<()> {
                require!(name.len() >= 3 && name.len() <= 32, Err::InvalidLen);
                        require!(
                                    name.chars().all(|c| c.is_alphanumeric() || c == '-'),
                                                Err::InvalidChar
                                                        );

                                                                let domain = &mut ctx.accounts.domain;
                                                                        let clock = Clock::get()?;

                                                                                domain.owner = ctx.accounts.owner.key();
                                                                                        domain.name = name;
                                                                                                domain.registered = clock.unix_timestamp;
                                                                                                        domain.expires = clock.unix_timestamp + YEAR_SECONDS;
                                                                                                                domain.active = true;

                                                                                                                        system_program::transfer(
                                                                                                                                    CpiContext::new(
                                                                                                                                                    ctx.accounts.system_program.to_account_info(),
                                                                                                                                                                    system_program::Transfer {
                                                                                                                                                                                        from: ctx.accounts.owner.to_account_info(),
                                                                                                                                                                                                            to: ctx.accounts.treasury.to_account_info(),
                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                    DOMAIN_COST,
                                                                                                                                                                                                                                                            )?;

                                                                                                                                                                                                                                                                    Ok(())
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                            pub fn renew(ctx: Context<Renew>) -> Result<()> {
                                                                                                                                                                                                                                                                                    let domain = &mut ctx.accounts.domain;
                                                                                                                                                                                                                                                                                            let clock = Clock::get()?;

                                                                                                                                                                                                                                                                                                    require!(domain.owner == ctx.accounts.owner.key(), Err::NotOwner);

                                                                                                                                                                                                                                                                                                            domain.expires = if domain.expires > clock.unix_timestamp {
                                                                                                                                                                                                                                                                                                                        domain.expires + YEAR_SECONDS
                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                            clock.unix_timestamp + YEAR_SECONDS
                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                            domain.active = true;

                                                                                                                                                                                                                                                                                                                                                                    system_program::transfer(
                                                                                                                                                                                                                                                                                                                                                                                CpiContext::new(
                                                                                                                                                                                                                                                                                                                                                                                                ctx.accounts.system_program.to_account_info(),
                                                                                                                                                                                                                                                                                                                                                                                                                system_program::Transfer {
                                                                                                                                                                                                                                                                                                                                                                                                                                    from: ctx.accounts.owner.to_account_info(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        to: ctx.accounts.treasury.to_account_info(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                DOMAIN_COST,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )?;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ok(())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn transfer(ctx: Context<Transfer>, new_owner: Pubkey) -> Result<()> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let domain = &mut ctx.accounts.domain;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let clock = Clock::get()?;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require!(domain.owner == ctx.accounts.owner.key(), Err::NotOwner);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        require!(domain.expires > clock.unix_timestamp, Err::Expired);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                domain.owner = new_owner;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Ok(())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub fn set_data(ctx: Context<SetData>, data: String) -> Result<()> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let domain = &mut ctx.accounts.domain;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let clock = Clock::get()?;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        require!(domain.owner == ctx.accounts.owner.key(), Err::NotOwner);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require!(domain.expires > clock.unix_timestamp, Err::Expired);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        domain.data = data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ok(())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #[account]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pub struct Domain {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub owner: Pubkey,   // 32
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pub name: String,    // 36 (4 + 32)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub registered: i64, // 8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pub expires: i64,    // 8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub active: bool,    // 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pub data: String,    // 132 (4 + 128)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #[derive(Accounts)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #[instruction(name: String)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pub struct Register<'info> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #[account(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        init,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                payer = owner,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        space = 8 + 32 + 36 + 8 + 8 + 1 + 132,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                seeds = [b"domain", name.as_bytes()],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bump
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub domain: Account<'info, Domain>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub owner: Signer<'info>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /// CHECK: Treasury
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pub treasury: AccountInfo<'info>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub system_program: Program<'info, System>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #[derive(Accounts)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub struct Renew<'info> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub domain: Account<'info, Domain>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub owner: Signer<'info>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /// CHECK: Treasury
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pub treasury: AccountInfo<'info>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub system_program: Program<'info, System>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #[derive(Accounts)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub struct Transfer<'info> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub domain: Account<'info, Domain>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pub owner: Signer<'info>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #[derive(Accounts)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pub struct SetData<'info> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #[account(mut)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pub domain: Account<'info, Domain>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub owner: Signer<'info>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #[error_code]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pub enum Err {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #[msg("Invalid length")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        InvalidLen,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #[msg("Invalid character")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                InvalidChar,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #[msg("Not owner")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NotOwner,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #[msg("Expired")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Expired,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
